application:
  port: 8080
  host: "127.0.0.1"

database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "postgres"
  require_ssl: false

email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my_secret_token"
